# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de839aa23a904ce83038096eb3e95ba305243f3f934961f47c0175674144f3775d01634e5431c30f6e5ab8f157e1a4d7527bb5ae134be620ffe2649e7b64aba4

test:
  secret_key_base: f18ea8bd4cbc5c1a168447e00bb95f0a5be6d5b0a9f190589c84a33e2dd5fa306402fbe5bd4b6ea0ac8428b385a736cc716c2db49e0dc2519a1c217c6d46ef1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
